### ISSUE TITLE
Space in Folder path causes app to exit. 

### ISSUE THREAD

**Issue by AetherCollective** [daemondevin/pac-man#1]
```
 (macro:!ECHO:3)
!searchparse /file: error opening "P:\Portable"
Error in script "P:\Portable Library\PortableApps\PortableAppsComiler\Other\Source\PortableAppsCompiler.nsi" on line 372 -- aborting creation process
ERROR: MakeNSIS exited with status code 1
```
Seems that you didn't put quote your path, thus the space in P:\Portable Library\ causes it to break.

**Comment by daemondevin** [comment]
I cannot seem to replicate your issue with my PortableApps Compiler. Everything compiles fine on my end and I used the same path you did. I'll keep trying on my end.

**Comment by daemondevin** [comment]
Are you using the latest build? Can you please try compiling another program and see what you come up with? Thanks.

**Comment by daemondevin** [comment]
@BetaLeaf This issue has been fixed. You can download the new files according to which branch you are using. Remember there are two branches of my PortableApps Compiler. The Development branch doesn't use the same environment variables as PA.c so you must be aware of that but the main branch of PortableApps Compiler does.

Thank you for helping. 

=)
